language: csharp
solution: TensorFlowSharp.sln
script:
  - tsh_version=1.4.0-pre1
  - wget "https://www.nuget.org/api/v2/package/TensorFlowSharp/$tsh_version"
  - tar xzvf $tsh_version native
  - dotnet restore
  - dotnet build -c Release
  - dotnet test -c Release --no-build
mono: "5.4.1"
dotnet: "2.1.4"
os: "osx"
