version: 1.8.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- cmd: dotnet restore TensorFlowSharp.CSharpOnly.sln
- cmd: curl "https://www.nuget.org/api/v2/package/TensorFlowSharp/1.4.0-pre1" -o native.zip
- cmd: 7z x native.zip
build:
  project: TensorFlowSharp.CSharpOnly.sln
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
